회원 운동 기록 기능 PR 요청
codestates-seb/seb39_main_024 pull request #21
Opened 2022-09-17 06:08 UTC by sungmingt

1. 회원 운동 기록 기능 추가
2. 해당 기능에 대한 테스트 코드 추가

2022-09-17 06:16 UTC, sungmingt reviewed
질문 comment 작성

2022-09-17 06:16 UTC, sungmingt commented on server/fly-away/src/main/java/com/codestates/flyaway/web/member/dto/MemberDto.java
> +public class MemberDto {
Dto를 내부 클래스로 구현하는 방식으로 학습해와서 무심코 사용했었는데,   이 방식에 문제가 없는지 궁금합니다!

2022-09-17 06:16 UTC, sungmingt commented on server/fly-away/src/main/java/com/codestates/flyaway/web/member/dto/MemberDto.java
> +        public static MemberProfileResponseDto memberToProfileResponse(Member member) {
엔티티 변환을 Dto 클래스 안에서 메서드로 사용해도 될까요?

2022-09-17 06:16 UTC, sungmingt commented on server/fly-away/src/main/java/com/codestates/flyaway/domain/record/entity/Record.java
> +    private String date;
현재 개발 단계에서만 사용할 h2 db에 날짜를 String 값으로 입력하도록 했는데, 이 방식에 문제가 없을까요? 
아니면 h2 날짜 타입으로 맞춰서 넣어야 할까요?

2022-09-17 06:58 UTC, Hyune-c requested changes
FEAT : add record insert logic

feature 라고 쓰여있지만 실제로는 설정부터 문서까지 모두 들어간 커밋 같습니다.

2022-09-17 06:58 UTC, Hyune-c commented on server/fly-away/src/main/java/com/codestates/flyaway/domain/member/entity/Member.java
> +@AllArgsConstructor  //
무의미한 주석은 삭제해주세요.

2022-09-17 06:58 UTC, Hyune-c commented on server/fly-away/src/main/java/com/codestates/flyaway/domain/member/entity/Member.java
> +    private List<Record> records = new ArrayList<>();
`cascade` 는 사용하지 않으면서 `orphanRemoval` 은 사용하는 경우는 처음 보는 것 같네요.
상당히 어려운 기술이니 사용하시기로 정했다면 테스트를 충분히 하는 것을 권장합니다.

2022-09-17 06:58 UTC, Hyune-c commented on server/fly-away/src/main/java/com/codestates/flyaway/domain/member/entity/Member.java
> +    private long totalRecord;
primitive 활용을 의도하신 건가요?
그렇다면 활용 이유도 말할 수 있었으면 좋겠습니다.

2022-09-17 06:58 UTC, Hyune-c commented on server/fly-away/src/main/java/com/codestates/flyaway/global/audit/Auditable.java
> +public abstract class Auditable {
`nit` Auditable 이라는 네이밍은 어떻게 생각하게 된 것인가요?

2022-09-17 06:58 UTC, Hyune-c commented on server/fly-away/src/main/java/com/codestates/flyaway/domain/member/service/MemberService.java
> +    //특정 회원을 모든 운동기록과 함께 조회 (회원 프로필)
`nit` 메서드 상단에 주석을 한다면 javadoc 형태를 권장합니다.

2022-09-17 06:58 UTC, Hyune-c commented on server/fly-away/src/main/java/com/codestates/flyaway/domain/member/service/MemberService.java
> +    public Member findById(long memberId) {
entity 가 controller 로 반환될 수 있는 메서드이네요.

2022-09-17 06:58 UTC, Hyune-c commented on server/fly-away/src/main/java/com/codestates/flyaway/domain/record/entity/Record.java
> +    private String date;
mysql 과 h2 모두에 호환되는 날짜 타입을 활용할 수 있지 않을까요?

2022-09-17 06:58 UTC, Hyune-c commented on server/fly-away/src/main/java/com/codestates/flyaway/domain/record/entity/Record.java
> +@NoArgsConstructor(access = PROTECTED)
👍

2022-09-17 06:58 UTC, Hyune-c commented on server/fly-away/src/main/java/com/codestates/flyaway/domain/member/service/MemberService.java
> +    public Member findById(long memberId) {
조회 메서드는 트랜잭션 타입을 조정할 수 있을 것 같습니다.

2022-09-17 06:58 UTC, Hyune-c commented on server/fly-away/src/main/java/com/codestates/flyaway/domain/record/service/RecordService.java
> +            Record record = findRecord.get();
Optional 을 좀 더 활용해주세요. 
`get()` 메서드는 존재하지 않는 메서드라고 간주하는 것이 좋습니다.

2022-09-17 06:58 UTC, Hyune-c commented on server/fly-away/src/main/java/com/codestates/flyaway/domain/record/service/RecordService.java
> +    }
`nit` 이 정도 크기의 if-else 라면 메서드 분리도 좋아보입니다.

2022-09-17 06:58 UTC, Hyune-c commented on server/fly-away/src/main/java/com/codestates/flyaway/web/member/dto/MemberDto.java
> +public class MemberDto {
네. 선호의 차이로 봐도 좋습니다.
하지만 제가 지금까지 경험한 팀은 모두 동일 패키지 아래 단일 클래스로 구성했던 것 같아요.

2022-09-17 06:58 UTC, Hyune-c commented on server/fly-away/src/main/java/com/codestates/flyaway/web/member/dto/MemberDto.java
> +        public static MemberProfileResponseDto memberToProfileResponse(Member member) {
많이 쓰이는 방법 중 하나입니다.
추가로 lazy loading 에 대한 테스트를 해보는 것을 권장합니다.

2022-09-17 06:58 UTC, Hyune-c commented on server/fly-away/src/test/java/com/codestates/flyaway/record/service/InsertRecordTest.java
> +@Transactional
https://velog.io/@tmdgh0221/%EC%8A%A4%ED%94%84%EB%A7%81-%ED%85%8C%EC%8A%A4%ED%8A%B8-%EC%BC%80%EC%9D%B4%EC%8A%A4%EC%97%90%EC%84%9C%EC%9D%98-Transactional-%EC%9C%A0%EC%9D%98%EC%A0%90

고민해주세요.

2022-09-17 06:58 UTC, Hyune-c commented on server/fly-away/src/test/java/com/codestates/flyaway/record/service/InsertRecordTest.java
> +                .orElseThrow(() -> new RuntimeException("RuntimeException!!!"));
`nit` test 에서는 코드 간소화를 위해 `get()` 을 활용하는 것도 방법입니다.

2022-09-17 07:51 UTC, sungmingt commented on server/fly-away/src/main/java/com/codestates/flyaway/domain/member/entity/Member.java
> +@AllArgsConstructor  //
무의미한 주석 삭제하도록 하겠습니다!

2022-09-17 07:51 UTC, sungmingt commented on server/fly-away/src/main/java/com/codestates/flyaway/domain/member/entity/Member.java
> +    private List<Record> records = new ArrayList<>();
단순히 member 삭제 시 record도 삭제되도록 하려고 한 것 같습니다.
더 공부해보고 사용 여부를 결정하도록 하겠습니다!

2022-09-17 07:51 UTC, sungmingt commented on server/fly-away/src/main/java/com/codestates/flyaway/domain/member/service/MemberService.java
> +    public Member findById(long memberId) {
앗 Dto를 반환하도록 수정하겠습니다!

2022-09-17 07:51 UTC, sungmingt commented on server/fly-away/src/main/java/com/codestates/flyaway/domain/member/service/MemberService.java
> +    public Member findById(long memberId) {
조회 메서드는 readOnly = true 로 변경하도록 하겠습니다!

2022-09-17 07:51 UTC, sungmingt commented on server/fly-away/src/main/java/com/codestates/flyaway/domain/member/service/MemberService.java
> +    //특정 회원을 모든 운동기록과 함께 조회 (회원 프로필)
javadoc 형태로 변경해보겠습니다!

2022-09-17 07:51 UTC, sungmingt commented on server/fly-away/src/main/java/com/codestates/flyaway/domain/record/entity/Record.java
> +    private String date;
호환되는 날짜 타입을 찾아보겠습니다!

2022-09-17 07:51 UTC, sungmingt commented on server/fly-away/src/main/java/com/codestates/flyaway/domain/record/service/RecordService.java
> +            Record record = findRecord.get();
isPresent() 메서드로 확인 후 호출한 거라 괜찮을 거라고 생각했네요.
다른 방법으로 수정해보겠습니다!

2022-09-17 07:51 UTC, sungmingt commented on server/fly-away/src/main/java/com/codestates/flyaway/domain/record/service/RecordService.java
> +    }
저도 단순히 지저분하다고 생각되어 메서드 분리를 생각했었는데, 재사용 할 일이 없을 것 같아 놔둔 것 같습니다.
다시 생각해보니 후에 재사용할 일이 생길 수도 있고, 가독성 측면에서도 분리하는 편이 좋을 것 같습니다.

2022-09-17 07:51 UTC, sungmingt commented on server/fly-away/src/main/java/com/codestates/flyaway/global/audit/Auditable.java
> +public abstract class Auditable {
학습 자료에서 사용했던 이름을 무심코 쭉 사용해왔습니다.

2022-09-17 07:51 UTC, sungmingt commented on server/fly-away/src/main/java/com/codestates/flyaway/web/member/dto/MemberDto.java
> +        public static MemberProfileResponseDto memberToProfileResponse(Member member) {
지연 로딩에 대한 테스트를 시도해보겠습니다!

2022-09-17 07:51 UTC, sungmingt commented on server/fly-away/src/test/java/com/codestates/flyaway/record/service/InsertRecordTest.java
> +@Transactional
와... 해당 부분은 미처 생각을 못했네요.
Transactional 애노테이션을 제외하고, rollback 메서드를 작성하여 테스트하는 방법을 시도해보겠습니다

2022-09-17 07:51 UTC, sungmingt commented on server/fly-away/src/test/java/com/codestates/flyaway/record/service/InsertRecordTest.java
> +                .orElseThrow(() -> new RuntimeException("RuntimeException!!!"));
테스트 코드에서는 get()을 활용해보도록 하겠습니다!

2022-09-17 07:51 UTC, sungmingt commented on server/fly-away/src/main/java/com/codestates/flyaway/domain/member/entity/Member.java
> +    private long totalRecord;
- 특별한 생각 없이 primitive을 사용한 것 같습니다.

- 검색해본 결과로는  "primitive 타입의 경우 값을 공유하지 않기 때문에 안전하게 다룰 수 있지만, 변경 시 추적이 불가능하다" 정도로만 이해했습니다. 

확실하게 이해가 되지 않아 헷갈리네요 ㅠ

2022-09-17 07:59 UTC, Hyune-c commented on server/fly-away/src/main/java/com/codestates/flyaway/domain/member/entity/Member.java
> +    private long totalRecord;
https://hyune.gitbook.io/hyune-wiki/framework-and-library/jpa/entity-field-type

참고해주세요.

2022-09-19 11:14 UTC, Hyune-c requested changes
conflict 상태인 pr 은 리뷰하지 않습니다.

2022-09-19 11:22 UTC, sungmingt commented
conflict 해결했습니다! pr 내용은 대부분 이전에 지적해주신 부분들 고친 내용입니다.

2022-09-20 04:25 UTC, merged